Create table Register (
 ID int NOT NULL IDENTITY(1,1) PRIMARY KEY,
 USERNAME varchar(50) NOT NULL,
 NAME varchar(50) NOT NULL,
 EMAIL varchar(100)  NOT NULL ,
 PASSWORD varchar(10) NOT NULL
 )


 Create table TweetsData (
 TWEETID int NOT NULL IDENTITY(100,1) PRIMARY KEY,
 USERID INT NOT NULL,
 USERNAME varchar(20),
 TWEETDESCRIPTION varchar(200) NOT NULL,
 CREATEDAT  DATETIME ,
 UPDATEDAT  DATETIME,
 COMMENTSCOUNT INT,
 LIKESCOUNT INT 
 )

